### PR TITLE
Add static Maybe.all

### PR DESCRIPTION
**Pull request by denis-sokolov**
I need this in daily work a lot. Please criticize or question, if you are unsure about this.

### CODE REVIEW

**Comment by cbowdon** [comment]
Thanks for these - I'll review as soon as I can.

**Comment by cbowdon** [comment]
Thanks for this and the other PRs, much appreciated! This is a really useful inclusion. 

I would actually like to take it a bit further, something like this:
https://github.com/cbowdon/TsMonad/commit/4cd44d6df4cddbc0cc46014015e8172d294686aa#diff-35b63254f0e06451e91af9b3948c532dR74 

In that branch I've made these changes:
- More strongly typed (can still be dynamic if you choose `any` as type parameter)
- Named after Haskell's `sequence`. The rest of the library generally chooses the Haskell names so it's good to be consistent. I don't mind adding in some aliases if you already laid down a lot of code using `all` though.
- Minor formatting changes, again in the name of consistency

Then there are some obvious future enhancements:
- `sequence` should be applicable to any Monad. It can probably be defined in terms of `bind` and `reduce`.
- It should also be applicable to any kind of collection, so there should be an overload for arrays too. (And maybe ES6 Maps/WeakMaps.)

How does that sound? Let me know if you'd like an `all` alias and I'll throw it in. Otherwise I'll add some more tests, update the README and merge the two commits in that branch then publish 0.5.0 to npm, aiming to do the extra stuff some time in the future. 

Again, many thanks for contributing. I am delighted to see real-world usage shaping this library. :-)

**Comment by denis-sokolov** [comment]
> More strongly typed (can still be dynamic if you choose any as type parameter)

`sequence({ name: maybeName, age: maybeAge })` fails compilation with ‘cannot be inferred from usage’, so, as you say, I need to `sequence<all>({ name: maybeName, age: maybeAge })`. Not a big deal, but also the benefit is not big either. After all, `sequence<string|number>` is not strict typing, and maps where all values are the same type are rare, maps are generally for varying data. To conclude, since both the cost and the benefit is small, I really don’t care.

> Named after Haskell's sequence.
> The rest of the library generally chooses the Haskell names so it's good to be consistent.

I like being consistent with Haskell, but I shall question whether it makes sense here. Haskell’s `sequence`, if [I understand correctly](https://en.wikibooks.org/wiki/Haskell/Libraries/Maybe#sequence), is amount a list of maybes. This makes sense given the name. We are discussing an unordered map of maybes, though. It’s a little bit strange to name it a sequence. Perhaps `Maybe.dictionary`, then?

I don't mind adding in some aliases if you already laid down a lot of code using all though.

> I don't mind adding in some aliases if you already laid down a lot of code using all though.

Me having a lot of code would be a weak reason. I can always `Maybe.all = Maybe.whatever` myself. I can always search and replace myself, it’s my problem. You should focus on the design of your API.

My original name `.all` was because of `Promise.all`, and I think it’s a great connection to have, as promises are kind of Maybe monads that are very familiar to JavaScript world. Now I realize that my connection was invalid, as `Promise.all` actually does work on lists, just like Haskell’s sequence.

So perhaps, we shall have a `Maybe.sequence` with an alias `Maybe.all`, that works on lists.

And then we can discuss a similar helper for dictionaries. `Maybe.dict`?

**Comment by denis-sokolov** [comment]
> then publish 0.5.0 to npm

I would ask and advise to release often. There is little value in grouping features, since releasing is so cheap. No matter our discussions, if you release 0.5.0, I can start using `.valueOf`.

**Comment by cbowdon** [comment]
Good points, I will respond properly tonight. Quick note about sequence in Haskell: there is a more abstract version that covers all `Traversables` (quite like collections):

http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Traversable.html#v:sequence

This is what I was getting at with the overloads for arrays/Map/WeakMap.

**Comment by denis-sokolov** [comment]
Ah, cool. Yeah, then your initial suggestion is great. I will want the `.all` alias, as I mentioned, for the similarity to `Promise.all` (and also for its much shorter name :P).

**Comment by cbowdon** [comment]
Good suggestion on publishing little and often. You're right there is no value in batching up non-breaking changes.

**Comment by cbowdon** [comment]
I've added more tests and the all alias. Seems good, but could you give `master` a whirl and let me know if you spot any issues with it please?

The array version is on my todo list. I was wrong about it applying to any monad, it should only be any traversable or foldable, so I'll just add similar static methods to Either rather than anything more sophisticated.

**Comment by denis-sokolov** [comment]
I will try it out!

**Comment by denis-sokolov** [comment]
The code looks nice if I use it this way:

``` ts
Maybe.sequence({
  userLimit: maybeUserLimit,
  users: maybeUsers
}).caseOf({
  just: (res) => res.userLimit - res.users.length,
  nothing: () => Maybe.just(NaN)
})
```

But this does not work. There are two typing problems.

One is that I need to enumerate all value types in sequence type parameter (`Maybe.sequence<number|User[]>({`). This quickly gets annoying, so I put in `any` anyway, defeating the purpose of the attempted typing on `.sequence`. =7 Maybe untype `.sequence` after all?

The second one is `res.users` is invalid access, as res is now only typed as indexed object `{ [k: string]: any }`. I am only allowed to `res['users']` which is much clunkier and gives no typing benefit.

As sad as it is, perhaps remove all typing on the `.sequence` (`{ [k: string]: any } => Maybe<any>`)?

**Comment by cbowdon** [comment]
Sorry for the delay in getting to this. I'm still quite keen on strong typing being an option, but how about this approach: 
`Maybe.all` becomes an alias for `Maybe.sequence<any>` ? It sort of seems appropriate that the JavaScript-ish alias is dynamically typed.

**Comment by denis-sokolov** [comment]
Well, my opinion is that you don’t have strong typing. TypeScript is not expressive enough to express the real type of Maybe.sequence. `Maybe.sequence<number|User[]>` is not strong, you can still make a mistake at passing the specific parameter keys, and the `res['users']` is still `any`. I have a few cases in my codebase where I have to accept that TypeScript does not express my intent, and that’s okay, at some point, you have to let it go.

`Maybe.all` being a dynamic alias would be perfect for me, so in the sense of my personal practical goals I don’t care about `.sequence` being typed and I would be very happy `Maybe.all`.

**Comment by cbowdon** [comment]
I take your point, but not sure I can let go ;-)

I'll add the alias and publish a new version, probably sometime in the next week.

**Pull request merged**
