### PR TITLE
Add documentation to definition file

### PR DESCRIPTION
**Pull request by ValentinTrinque**
PR for #2 

Here is the documentation need by DefinitelyTyped to be truly compliant.

Need to be reviewed in order to prevent misleading documentation.

### CODE REVIEW

**Comment by ValentinTrinque** [comment]
Any news ?

**Comment by cbowdon** [comment]
Wow, thank you! They all look correct, nice job. One change to make: the docs should be on the .ts source files rather than the .d.ts (as the .d.ts is auto-generated from the sources).

**Comment by ValentinTrinque** [comment]
Auto-generate ? =O Ok, got it !

**Comment by ValentinTrinque** [comment]
I think we are good now. I tried to use lodash template to autogenerate the header with the info inside the `package.json` but couldn't succeed. Maybe a future improvement.

**Comment by cbowdon** [comment]
This looks great, I'll test it as soon as I can. :+1:

**Comment by ValentinTrinque** [comment]
Once you've tested it, I will PR  DefinitelyTyped repository and your lib will become usable through `tsd`. =)

**Comment by cbowdon** [comment]
Tested - all good. Thanks Valentin!

**Pull request merged**
